### ISSUE TITLE
How to Configure Diginetica dataset to run in the framework

### ISSUE THREAD

**Issue by TauraiUCB** [rn5l/session-rec#32]
I have processed Diginetica data by running `python run_preprocessing.py conf/preprocess/session_based/window/diginetica.yml` and obtained several files such as `train-item-views_train_full.0`. I renamed the folder from `data/diginetica/slices` to `data/diginetica/prepared`. 
After preprocessing the data, I used `conf/example_all_neural.yml` and configured it for diginetica data by changing `yml` file to look as follows
```
type: single # single|window|opt
key: baselines_and_models #added to the csv names
evaluation: evaluation_user_based # evaluation_user_based
data:
  name: diginetica #added in the end of the csv names
  folder: data/diginetica/prepared/
  prefix: train-item-views
  type: csv # hdf|csv(default)

results:
  folder: results/session-aware/diginetica/
```
After that I ran `THEANO_FLAGS="device=cuda0,floatX=float32" CUDA_DEVICE_ORDER=PCI_BUS_ID python run_config.py conf/example_all_neural.yml`  and I am getting an error that says
```
Using TensorFlow backend.
init
Traceback (most recent call last):
  File "run_config.py", line 62, in main
    run_file(c)
  File "run_config.py", line 164, in run_file
    run_single(conf)
  File "run_config.py", line 213, in run_single
    m.init(train)
UnboundLocalError: local variable 'train' referenced before assignment

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "run_config.py", line 919, in <module>
    main(sys.argv[1], out=sys.argv[2] if len(sys.argv) > 2 else None)
  File "run_config.py", line 73, in main
    print('error for config ', list[0])
UnboundLocalError: local variable 'list' referenced before assignment
```

I have tested my `srec37` environment on `yoochoose` data and it trains without a problem. I am wondering what is wrong with `diginetica` configuration, or I might have skipped or overlooked something.

**Comment by saraLatifi** [comment]
Here, the problem is that by `python run_preprocessing.py conf/preprocess/session_based/window/diginetica.yml`, you are preprocessing **diginetica** for the **session_based** scenario (and **window** evaluation), but in **conf/example_all_neural.yml**, by `type: single` & `evaluation: evaluation_user_based`, you are using it in the **session_aware** scenario (and **single** evaluation). Therefore, you get an error because the prepared data (in data/diginetica/prepared) does not match the evaluation in the configuration file (example_all_neural.yml).
